# Generated by Django 4.0.2 on 2022-02-28 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cust',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('pwd', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'db_cust',
            },
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('imgname', models.CharField(blank=True, max_length=20, null=True)),
                ('regdate', models.DateField()),
            ],
            options={
                'db_table': 'db_item',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(blank=True, null=True)),
                ('regdate', models.DateField(auto_now=True)),
                ('custid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custid', to='web.cust')),
                ('itemid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemid', to='web.item')),
            ],
            options={
                'db_table': 'db_cart',
            },
        ),
    ]
